fix(adb): support for custom adb server tcp port
https://github.com/2moe/tmoe-linux/issues/143

diff --git a/share/old-version/share/termux/fix_signal9 b/share/old-version/share/termux/fix_signal9
--- a/share/old-version/share/termux/fix_signal9
+++ b/share/old-version/share/termux/fix_signal9
@@ -85,15 +85,34 @@ adb_pair_or_connect() {
         adb pair "$ADB_ADDRESS"
     fi
     adb connect "$ADB_ADDRESS"
+    adb devices -l
 }
 do_you_want_to_restart_adb_server() {
     if (whiptail --title "adb kill-server" --yes-button "Yes" --no-button "No" --yesno "Do you want to restart the adb server?" 0 50); then
         adb kill-server
     fi
 }
+do_you_want_to_change_the_adb_server_tcp_port() {
+    if (whiptail --title "adb server tcp port" --yes-button "Yes" --no-button "No" --yesno "Do you want to set the adb server port to \"50377\"?\nNote: The adb server port is not the adb device port.\nThe deafult adb server port is 5037.\nBut in tmoe, it is 50377." 0 50); then
+        ANDROID_ADB_SERVER_PORT=50377
+    else
+        ANDROID_ADB_SERVER_PORT=$(whiptail --inputbox "Please type a tcp port(1024~65535)" 0 50 --title "ADB SERVER PORT" 3>&1 1>&2 2>&3)
+        if [ "$?" != "0" ]; then
+            printf "%s\n" "${YELLOW}Unknown ${RED}ERROR${RESET}"
+            ANDROID_ADB_SERVER_PORT=50378
+        elif [ -z "${ADB_ADDRESS}" ]; then
+            ANDROID_ADB_SERVER_PORT=50379
+        fi
+    fi
+    printf "%s\n" "Your ANDROID_ADB_SERVER_PORT is ${ANDROID_ADB_SERVER_PORT}"
+    export ANDROID_ADB_SERVER_PORT
+}
+
 connect_to_adb_device() {
     adb --version
     do_you_want_to_restart_adb_server
+    do_you_want_to_change_the_adb_server_tcp_port
+    # ANDROID_ADB_SERVER_PORT
     adb_pair_or_connect
     ADB_LIST="$(adb devices | wc -l)"
     case ${ADB_LIST} in
