+micro

diff --git a/share/old-version/tools/app/tool b/share/old-version/tools/app/tool
--- a/share/old-version/tools/app/tool
+++ b/share/old-version/tools/app/tool
@@ -92,7 +92,7 @@ check_tmoe_command() {
 	else
 		TMOE_TIPS_01="tmoe t"
 	fi
-	TMOE_TIPS_00="Welcome to tmoe linux tool v1.4756,type ${TMOE_TIPS_01} to start this tool."
+	TMOE_TIPS_00="Welcome to tmoe linux tool v1.4757,type ${TMOE_TIPS_01} to start this tool."
 	#勿改00变量
 }
 #########
@@ -623,10 +623,14 @@ check_dependencies() {
 		*)
 			printf "%s\n" "${RED}Sorry${RESET},tmoe-linux tool does not support your distro. If you want to report a bug, please go to ${BLUE}github.${YELLOW}https://github.com/2moe/tmoe-linux${RESET}"
 			printf "%s\n" "${RED}不支持${RESET}您当前的发行版，您可以前往${YELLOW}https://github.com/2moe/tmoe-linux${RESET}提交issue,并附上${BLUE}cat /etc/os-release${RESET}的截图。"
+			uname -a
+			# sleep 2
+			# exit 1
 			press_enter_to_continue
-			apt update
-			${TMOE_INSTALLATION_COMMAND} ${DEPENDENCIES}
-			apt install -y ${DEPENDENCIES} || port install ${DEPENDENCIES} || guix package -i ${DEPENDENCIES} || pkg install ${DEPENDENCIES} || pkg_add ${DEPENDENCIES} || pkgutil -i ${DEPENDENCIES} || pacman -Syu ${DEPENDENCIES}
+			# apt update
+			# ${TMOE_INSTALLATION_COMMAND} ${DEPENDENCIES}
+			# apt install -y ${DEPENDENCIES} ||
+			pkg install ${DEPENDENCIES} || port install ${DEPENDENCIES} || guix package -i ${DEPENDENCIES} || pkg_add ${DEPENDENCIES} || pkgutil -i ${DEPENDENCIES} || pacman -Syu ${DEPENDENCIES}
 			;;
 		esac
 	fi
@@ -680,9 +684,22 @@ check_dependencies() {
 		esac
 		;;
 	esac
+	if [[ ! $(command -v micro) && ! -e "${TMOE_LINUX_DIR}/not_install_micro" ]]; then
+		printf "%s\n" "${GREEN}${TMOE_INSTALLATION_COMMAND} ${BLUE}micro${RESET}"
+		${TMOE_INSTALLATION_COMMAND} micro
+		# MICRO_VERSION="2.0.9"
+		mkdir -pv ${TMOE_LINUX_DIR}
+		if [ ! $(command -v micro) ]; then
+			touch ${TMOE_LINUX_DIR}/not_install_micro
+		else
+			update-alternatives --install /usr/bin/editor editor /usr/bin/micro 30
+			update-alternatives --set editor /usr/bin/micro
+			# update-alternatives --auto editor
+			printf "%s\n" "You can type ${RED}sudo ${GREEN}update-alternatives ${YELLOW}--config ${BLUE}editor${RESET} to set your default editor."
+		fi
+	fi
 	if [ ! $(command -v catimg) ] && [ ! -e "${TMOE_LINUX_DIR}/not_install_catimg" ]; then
 		mkdir -pv ${TMOE_LINUX_DIR}
-		touch ${TMOE_LINUX_DIR}/not_install_catimg
 		case "${LINUX_DISTRO}" in
 		debian)
 			CATIMG_REPO="https://mirrors.bfsu.edu.cn/debian/pool/main/c/catimg/"
@@ -694,6 +711,9 @@ check_dependencies() {
 			fi
 			;;
 		esac
+		if [ ! $(command -v catimg) ]; then
+			touch ${TMOE_LINUX_DIR}/not_install_catimg
+		fi
 	fi
 	################
 	if [ "$(uname -r | cut -d '-' -f 3)" = "Microsoft" ] || [ "$(uname -r | cut -d '-' -f 2)" = "microsoft" ]; then
