style(space): 1 tab -> 4 spaces

diff --git a/share/old-version/share/container/chroot/notes b/share/old-version/share/container/chroot/notes
--- a/share/old-version/share/container/chroot/notes
+++ b/share/old-version/share/container/chroot/notes
@@ -1,52 +1,52 @@
 #!/usr/bin/env bash
 #######################################
 check_root_permissions() {
-	case ${LINUX_DISTRO} in
-	Android)
-		su -c "ls ${HOME} >/dev/null"
-		case "$?" in
-		0)
-			if [ ! "$(command -v sudo)" ] && [ ! "$(command -v tsu)" ]; then
-				printf "%s\n" "${GREEN}apt install -y${RESET} ${BLUE}tsu${RESET}"
-				printf "%s\n" "You can type ${RED}apt purge${RESET} ${BLUE}tsu${RESET} to remove it."
-				apt update
-				apt install -y tsu
-			fi
-			if [[ ! -e ${PREFIX}/bin/sudo && -e ${PREFIX}/bin/tsudo ]]; then
-				ln -svf "${PREFIX}"/bin/tsudo "${PREFIX}"/bin/sudo
-			fi
-			;;
-		*)
-			printf "%s\n" "Android :${BLUE}${ANDROID_VERSION}${RESET}"
-			printf "%s\n" "$(getprop ro.product.model)" 2>/dev/null
-			printf "%s\n" "${RED}ERROR${RESET},检测到root权限${PURPLE}授予失败${RESET}，您无法通过tmoe linux manager安装${BLUE}chroot${RESET}容器"
-			press_enter_to_return
-			tmoe_manager_main_menu
-			;;
-		esac
-		;;
-	esac
+    case ${LINUX_DISTRO} in
+    Android)
+        su -c "ls ${HOME} >/dev/null"
+        case "$?" in
+        0)
+            if [ ! "$(command -v sudo)" ] && [ ! "$(command -v tsu)" ]; then
+                printf "%s\n" "${GREEN}apt install -y${RESET} ${BLUE}tsu${RESET}"
+                printf "%s\n" "You can type ${RED}apt purge${RESET} ${BLUE}tsu${RESET} to remove it."
+                apt update
+                apt install -y tsu
+            fi
+            if [[ ! -e ${PREFIX}/bin/sudo && -e ${PREFIX}/bin/tsudo ]]; then
+                ln -svf "${PREFIX}"/bin/tsudo "${PREFIX}"/bin/sudo
+            fi
+            ;;
+        *)
+            printf "%s\n" "Android :${BLUE}${ANDROID_VERSION}${RESET}"
+            printf "%s\n" "$(getprop ro.product.model)" 2>/dev/null
+            printf "%s\n" "${RED}ERROR${RESET},检测到root权限${PURPLE}授予失败${RESET}，您无法通过tmoe linux manager安装${BLUE}chroot${RESET}容器"
+            press_enter_to_return
+            tmoe_manager_main_menu
+            ;;
+        esac
+        ;;
+    esac
 }
 #################
 notes_of_chroot() {
-	printf "%s\n %s\n" "If you find that some directories cannot be unmounted forcibly before removing the container,then please restart your device." "移除容器前若发现部分已挂载目录无法强制卸载，请重启设备再卸载chroot容器，防止已挂载目录被误删！" >"${CONFIG_FOLDER}"/chroot-prompt
-	sed -n p "${CONFIG_FOLDER}"/chroot-prompt
-	case ${LINUX_DISTRO} in
-	Android)
-		printf "%s\n" "If you can not use this function,try using magisk manager."
-		printf "%s\n" "您使用的是${YELLOW}Android${RESET}系统，ROOT环境${PURPLE}要求${RESET}：${BLUE}magisk(面具)${RESET}"
-		sleep 1
-		if ((ANDROID_VERSION <= 7)); then
-			printf "%s\n" "您的系统版本低于${BLUE}Android8${RESET},${PURPLE}可能无法${RESET}使用${YELLOW}tmoe-linux的chroot容器${RESET}配置功能。"
-			printf "%s\n" "Your android system version is lower than 8."
-			sleep 3
-		fi
-		;;
-	*)
-		printf "%s\n" "由于在测试chroot容器的过程中出现了部分已挂载的目录${RED}无法强制卸载${RESET}的情况，故建议您换用${BLUE}docker${RESET}容器。"
-		printf "%s\n" "We recommend that you run ${BLUE}docker${RESET} containers on GNU/Linux system instead of ${RED}chroot${RESET} containers."
-		;;
-	esac
+    printf "%s\n %s\n" "If you find that some directories cannot be unmounted forcibly before removing the container,then please restart your device." "移除容器前若发现部分已挂载目录无法强制卸载，请重启设备再卸载chroot容器，防止已挂载目录被误删！" >"${CONFIG_FOLDER}"/chroot-prompt
+    sed -n p "${CONFIG_FOLDER}"/chroot-prompt
+    case ${LINUX_DISTRO} in
+    Android)
+        printf "%s\n" "If you can not use this function,try using magisk manager."
+        printf "%s\n" "您使用的是${YELLOW}Android${RESET}系统，ROOT环境${PURPLE}要求${RESET}：${BLUE}magisk(面具)${RESET}"
+        sleep 1
+        if ((ANDROID_VERSION <= 7)); then
+            printf "%s\n" "您的系统版本低于${BLUE}Android8${RESET},${PURPLE}可能无法${RESET}使用${YELLOW}tmoe-linux的chroot容器${RESET}配置功能。"
+            printf "%s\n" "Your android system version is lower than 8."
+            sleep 3
+        fi
+        ;;
+    *)
+        printf "%s\n" "由于在测试chroot容器的过程中出现了部分已挂载的目录${RED}无法强制卸载${RESET}的情况，故建议您换用${BLUE}docker${RESET}容器。"
+        printf "%s\n" "We recommend that you run ${BLUE}docker${RESET} containers on GNU/Linux system instead of ${RED}chroot${RESET} containers."
+        ;;
+    esac
 }
 #############
 #此处不要加$@
diff --git a/share/old-version/share/container/common b/share/old-version/share/container/common
--- a/share/old-version/share/container/common
+++ b/share/old-version/share/container/common
@@ -1,89 +1,89 @@
 #!/usr/bin/env bash
 ##########################
 startvnc_or_enter_the_container() {
-	if [ -e "${DEBIAN_CHROOT}/usr/local/bin/startvnc" ]; then
-		cat <<-EOFVNC
+    if [ -e "${DEBIAN_CHROOT}/usr/local/bin/startvnc" ]; then
+        cat <<-EOFVNC
 			You can type ${GREEN}startvnc${RESET} to start ${BLUE}tight/tigervnc server${RESET},type ${RED}stopvnc${RESET} to stop it.
 			You can also type ${GREEN}debian-i${RESET} to start ${BLUE}Tmoe-linux tool.${RESET}
 		EOFVNC
-		[[ "${LINUX_DISTRO}" != 'Android' ]] || printf "%s\n" "在Android宿主机的Termux原系统下输${GREEN}startvnc${RESET}将同时启动Android版Realvnc viewer和${DEBIAN_FOLDER}容器内的tight或tiger vnc服务，输${GREEN}debian${RESET}仅支持进入${BLUE}${DEBIAN_FOLDER}容器${RESET}。"
-		startx11vnc
-	else
-		cat <<-EOFDEB
+        [[ "${LINUX_DISTRO}" != 'Android' ]] || printf "%s\n" "在Android宿主机的Termux原系统下输${GREEN}startvnc${RESET}将同时启动Android版Realvnc viewer和${DEBIAN_FOLDER}容器内的tight或tiger vnc服务，输${GREEN}debian${RESET}仅支持进入${BLUE}${DEBIAN_FOLDER}容器${RESET}。"
+        startx11vnc
+    else
+        cat <<-EOFDEB
 			You can type ${GREEN}debian${RESET} to enter the ${BLUE}${DEBIAN_FOLDER} container${RESET}.
 			You can also type ${GREEN}debian-i${RESET} to start ${BLUE}Tmoe-linux tool${RESET}.
 		EOFDEB
-		debian
-	fi
+        debian
+    fi
 }
 #######################
 install_gnu_linux_container() {
-	#此处不能用变量debian_chroot
-	if [ -d ${HOME}/${DEBIAN_FOLDER} ] && [ ! -e ${TMOE_CONTAINER_DIR} ]; then
-		source ${TMOE_SHARE_DIR}/deprecated/remove
-		if (whiptail --title "检测到您已安装${ROOTFS_NAME}容器,请选择您需要执行的操作！" --yes-button 'Start启动o(*￣▽￣*)o' --no-button 'Reinstall重装(っ °Д °)' --yesno "${ROOTFS_NAME} has been installed, please choose what you need to do" 0 0); then
-			#debian
-			startvnc_or_enter_the_container
-		else
-			printf "%s\n" "${YELLOW}检测到您已安装${ROOTFS_NAME}容器,是否重新安装？[Y/n]${RESET} "
-			printf "%s\n" "${YELLOW}您可以无需输"y"，直接按回车键确认。${RESET} "
-			printf "%s\n" "Detected that you have ${ROOTFS_NAME} container installed, do you want to reinstall it?${PURPLE}[Y/n]${RESET}"
-			read -r opt
-			case $opt in
-			y* | Y* | "")
-				remove_old_version_gnu_linux_container
-				if [ "$?" != '0' ]; then
-					printf "%s\n" "${ROOTFS_NAME}容器没有被移除"
-					press_enter_to_return
-					tmoe_manager_main_menu
-				else
-					if [ -d "${HOME}/debian_arm64" ]; then
-						printf '%s\n' '正在强制删除'
-						remove_old_version_gnu_linux_container
-					fi
-					check_and_view_the_eula
-				fi
-				;;
-			n* | N*)
-				printf "%s\n" "skipped."
-				press_enter_to_return
-				tmoe_manager_main_menu
-				;;
-			*)
-				printf "%s\n" "Invalid choice. skipped."
-				press_enter_to_return
-				tmoe_manager_main_menu
-				;;
-			esac
-		fi
+    #此处不能用变量debian_chroot
+    if [ -d ${HOME}/${DEBIAN_FOLDER} ] && [ ! -e ${TMOE_CONTAINER_DIR} ]; then
+        source ${TMOE_SHARE_DIR}/deprecated/remove
+        if (whiptail --title "检测到您已安装${ROOTFS_NAME}容器,请选择您需要执行的操作！" --yes-button 'Start启动o(*￣▽￣*)o' --no-button 'Reinstall重装(っ °Д °)' --yesno "${ROOTFS_NAME} has been installed, please choose what you need to do" 0 0); then
+            #debian
+            startvnc_or_enter_the_container
+        else
+            printf "%s\n" "${YELLOW}检测到您已安装${ROOTFS_NAME}容器,是否重新安装？[Y/n]${RESET} "
+            printf "%s\n" "${YELLOW}您可以无需输"y"，直接按回车键确认。${RESET} "
+            printf "%s\n" "Detected that you have ${ROOTFS_NAME} container installed, do you want to reinstall it?${PURPLE}[Y/n]${RESET}"
+            read -r opt
+            case $opt in
+            y* | Y* | "")
+                remove_old_version_gnu_linux_container
+                if [ "$?" != '0' ]; then
+                    printf "%s\n" "${ROOTFS_NAME}容器没有被移除"
+                    press_enter_to_return
+                    tmoe_manager_main_menu
+                else
+                    if [ -d "${HOME}/debian_arm64" ]; then
+                        printf '%s\n' '正在强制删除'
+                        remove_old_version_gnu_linux_container
+                    fi
+                    check_and_view_the_eula
+                fi
+                ;;
+            n* | N*)
+                printf "%s\n" "skipped."
+                press_enter_to_return
+                tmoe_manager_main_menu
+                ;;
+            *)
+                printf "%s\n" "Invalid choice. skipped."
+                press_enter_to_return
+                tmoe_manager_main_menu
+                ;;
+            esac
+        fi
 
-	else
-		check_and_view_the_eula
-	fi
+    else
+        check_and_view_the_eula
+    fi
 }
 ################################################
 check_and_view_the_eula() {
-	case ${TMOE_CHROOT} in
-	false) rm -f ${CONFIG_FOLDER}/chroot_container 2>/dev/null ;;
-	true) touch ${CONFIG_FOLDER}/chroot_container ;;
-	esac
+    case ${TMOE_CHROOT} in
+    false) rm -f ${CONFIG_FOLDER}/chroot_container 2>/dev/null ;;
+    true) touch ${CONFIG_FOLDER}/chroot_container ;;
+    esac
 
-	[[ -e "${CONFIG_FOLDER}/eula-v1.2.txt" ]] || tmoe_linux_container_eula
-	source ${TMOE_SHARE_DIR}/container/menu
+    [[ -e "${CONFIG_FOLDER}/eula-v1.2.txt" ]] || tmoe_linux_container_eula
+    source ${TMOE_SHARE_DIR}/container/menu
 }
 ########################
 tmoe_linux_container_eula() {
-	if [ ! -d "${DEBIAN_CHROOT}" ]; then
-		#less -meQ
-		sed -n p ${TMOE_GIT_DIR}/License
-		cat <<-EOF
+    if [ ! -d "${DEBIAN_CHROOT}" ]; then
+        #less -meQ
+        sed -n p ${TMOE_GIT_DIR}/License
+        cat <<-EOF
 			You must agree to the EULA to continue.
 			Press ${GREEN}Enter${RESET} to agree ${BLUE}the EULA${RESET}, otherwise press ${YELLOW}Ctrl + C${RESET} or ${RED}close${RESET} the terminal directly.
 			按${GREEN}回车键${RESET}同意${BLUE}《最终用户许可协议》${RESET} ，否则请按${YELLOW}Ctrl+C${RESET} 或直接${RED}关闭${RESET}终端。 
 		EOF
-		read -r
-		echo "You have agreed to this Agreement and its additional agreements." >${CONFIG_FOLDER}/eula-v1.2.txt
-	fi
+        read -r
+        echo "You have agreed to this Agreement and its additional agreements." >${CONFIG_FOLDER}/eula-v1.2.txt
+    fi
 }
 #############
 install_gnu_linux_container
diff --git a/share/old-version/share/container/remove b/share/old-version/share/container/remove
--- a/share/old-version/share/container/remove
+++ b/share/old-version/share/container/remove
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 #######################################
 tips_of_umount_chroot_container_02() {
-	cat <<-EOF
+    cat <<-EOF
 		${YELLOW}Q:为什么卸载chroot容器需要如此谨慎？${RESET}
 		A:此处引用umount的用户手册。
 		${GREEN}Note that a filesystem cannot be unmounted when it is 'busy' - for example, when there are open files on it, or when some process
@@ -27,7 +27,7 @@ tips_of_umount_chroot_container_02() {
 }
 ##############
 tips_of_umount_chroot_container_01() {
-	cat <<-EOF
+    cat <<-EOF
 		移除容器前，请先确保您unmounted了容器mounted目录。
 		建议您在移除前进行备份，若因操作不当而导致数据丢失，开发者${RED}概不负责${RESET}！！！
 		Before removing the container, make sure you have unmounted ${BLUE}dev dev/shm dev/pts proc sys root/sd media/sd media/tf${RESET} and other directories.
@@ -37,105 +37,105 @@ tips_of_umount_chroot_container_01() {
 }
 ###########
 remove_gnu_linux_container() {
-	case ${TMOE_CHROOT} in
-	true)
-		tips_of_umount_chroot_container_01
-		#source ${TMOE_SHARE_DIR}/removal/umount &>/dev/null
-		tips_of_umount_chroot_container_02
-		;;
-	esac
-	if [ "$(ls ${DEBIAN_CHROOT}/proc 2>/dev/null)" ]; then
-		printf "%s\n" "检测到proc目录不为空，无法继续卸载"
-		printf "%s\n" "Please restart the device to unmount the ${DEBIAN_CHROOT}/${i} directory."
-		printf "为防止目录被清空，请退出！！！"
-		press_enter_to_return
-		exit 1
-	fi
+    case ${TMOE_CHROOT} in
+    true)
+        tips_of_umount_chroot_container_01
+        #source ${TMOE_SHARE_DIR}/removal/umount &>/dev/null
+        tips_of_umount_chroot_container_02
+        ;;
+    esac
+    if [ "$(ls ${DEBIAN_CHROOT}/proc 2>/dev/null)" ]; then
+        printf "%s\n" "检测到proc目录不为空，无法继续卸载"
+        printf "%s\n" "Please restart the device to unmount the ${DEBIAN_CHROOT}/${i} directory."
+        printf "为防止目录被清空，请退出！！！"
+        press_enter_to_return
+        exit 1
+    fi
 
-	cd ${HOME}
-	for i in dev/shm dev/pts proc sys storage/emulated/0/* media/sd media/tf; do
-		if [ -e "${DEBIAN_CHROOT}/${i}" ]; then
-			ls -lAh "${DEBIAN_CHROOT}/${i}" 2>/dev/null
-		fi
-	done
-	unset i
-	check_rootfs_dir
-	grep ${DEBIAN_CHROOT} /proc/mounts
-	pkill -9 proot 2>/dev/null
-	pkill -9 chroot 2>/dev/null
-	ps -e | grep proot
-	ps -e | grep startvnc
-	printf "%s\n" "移除容器前，本工具将${RED}自动停止${RESET}${BLUE}${DEBIAN_FOLDER}${RESET}容器所运行的${GREEN}所有进程${RESET}。"
-	printf "%s\n" "Tmoe-linux manager will ${RED}automatically stop${RESET} ${GREEN}all processes${RESET} running in the ${BLUE}${DEBIAN_FOLDER}${RESET} container, and unmount the container directory."
-	pgrep proot &>/dev/null
-	if [ "$?" = "0" ]; then
-		printf '%s\n' '检测到proot容器正在运行，请先输stopvnc或手动强制停止容器运行'
-		#printf "%s\n" "若${ROOTFS_NAME}容器未停止运行，则建议你先手动在容器中执行stopvnc，再进行移除操作。"
-	fi
-	ls -l ${DEBIAN_CHROOT}/media/termux/* 2>/dev/null
-	if [ "$?" = "0" ]; then
-		printf '%s\n' 'WARNING！检测到/media/termux无法强制卸载，您当前使用的可能是chroot容器'
-		printf "%s\n" "若为误报，则请先停止容器进程，再手动移除${DEBIAN_CHROOT}/media/sd"
-		printf '%s\n' '建议您在移除前进行备份，若因操作不当而导致数据丢失，开发者概不负责！！！'
-	fi
-	printf "%s\n" "Detecting container size... 正在检测${ROOTFS_NAME}容器占用空间大小"
-	${TMOE_PREFIX} du -sh ${DEBIAN_CHROOT} --exclude=${DEBIAN_CHROOT}/media/tf --exclude=${DEBIAN_CHROOT}/media/sd --exclude=${DEBIAN_CHROOT}/media/termux 2>/dev/null
-	if [ ! -d ${DEBIAN_CHROOT} ]; then
-		printf "%s\n" "${YELLOW}It is detected that you do not currently have GNU/Linux container installed. 检测到您当前未安装容器${RESET}"
-	fi
-	printf "%s\n" "Press ${GREEN}enter${RESET} to ${RED}remove${RESET}."
-	printf "%s\n" "按${GREEN}回车键${RESET}确认${RED}移除${RESET}"
-	printf "%s\n" "Do you want to remove it?${PURPLE}[Y/n]${RESET}"
-	read -r opt
-	case $opt in
-	y* | Y* | "")
-		#non-rm "${CONFIG_FOLDER}/chroot_container"
-		case ${TMOE_CHROOT} in
-		true)
-			sudo rm -rfv ${PREFIX}/bin/debian-rm ${PREFIX}/bin/code ~/.config/tmoe-linux/across_architecture_container.txt "${DEBIAN_CHROOT}"
-			sudo chmod 777 -Rv ${DEBIAN_CHROOT}
-			;;
-		*)
-			rm -rfv ${PREFIX}/bin/debian-rm ${PREFIX}/bin/code ~/.config/tmoe-linux/across_architecture_container.txt "${DEBIAN_CHROOT}"
-			for i in ${PREFIX}/bin/debian-rm ${PREFIX}/bin/code ~/.config/tmoe-linux/across_architecture_container.txt; do
-				[[ ! -e ${i} ]] || sudo rm -rfv ${i}
-			done
-			chmod 777 -Rv ${DEBIAN_CHROOT} || sudo chmod 777 -Rv ${DEBIAN_CHROOT}
-			;;
-		esac
-		rm -rfv "${DEBIAN_CHROOT}" || sudo rm -rfv "${DEBIAN_CHROOT}"
-		printf "%s\n" "如需删除（通用的）启动脚本，则请手动输${RED}rm -fv ${BLUE}${PREFIX}/bin/debian ${PREFIX}/bin/novnc ${PREFIX}/bin/debian-i ${PREFIX}/bin/tmoe ${PREFIX}/bin/startvnc ${PREFIX}/bin/startx11vnc ${PREFIX}/bin/stopvnc ${PREFIX}/bin/startxsdl${RESET}"
-		sed -i '/alias debian=/d ; /alias debian-rm=/d' ${PREFIX}/etc/profile 2>/dev/null
-		source profile >/dev/null 2>&1
-		#printf '%s\n' 'The container has been removed. If you want to uninstall aria2, enter "apt remove aria2" or "apt purge aria2"'
-		#printf '%s\n' '移除完成，如需卸载aria2,请手动输apt remove aria2'
-		printf "%s\n" "Deleted已删除"
-		;;
-	n* | N*) printf "%s\n" "skipped." ;;
-	*) printf "%s\n" "Invalid choice. skipped." ;;
-	esac
-	#printf "%s\n" "若需删除tmoe-linux管理器，则请输rm -f ${PREFIX}/bin/debian-i"
-	printf '%s\n' 'If you want to reinstall, it is not recommended to remove the image file.'
-	printf "%s\n" "${YELLOW}若您需要重装容器，则不建议删除镜像文件。${RESET} "
-	cd ${ROOTFS_DIR}
-	DISTRO_ROOTFS_NAME=$(printf "%s\n" "${ROOTFS_NAME}" | cut -d '-' -f 1)
-	#${ROOTFS_NAME}*-rootfs.tar.*
-	ls -lh ${DISTRO_ROOTFS_NAME}*${ARCH_TYPE}*-rootfs.tar.* 2>/dev/null
-	printf "%s\n" "${YELLOW}请问您是否需要删除${BLUE}容器镜像文件？${PURPLE}[Y/n]${RESET} "
-	printf "%s\n" "${RED}rm -fv ${BLUE}${DISTRO_ROOTFS_NAME}*${ARCH_TYPE}*-rootfs.tar.*${RESET}"
-	printf "%s\n" "Do you need to delete the image file (${BLUE}${DISTRO_ROOTFS_NAME}*${ARCH_TYPE}*-rootfs.tar.*${RESET})?${PURPLE}[Y/n]${RESET}"
-	read -r opt
-	case $opt in
-	y* | Y* | "")
-		#rm -fv ${DEBIAN_CHROOT}*-rootfs.tar.*
-		#此处应删除ROOTFS_NAME而非DEBIAN_FOLDER开头的rootfs文件
-		rm -fv ${ROOTFS_DIR}/${DISTRO_ROOTFS_NAME}*${ARCH_TYPE}*-rootfs.tar.*
-		printf "%s\n" "Deleted已删除"
-		;;
-	n* | N*) printf "%s\n" "${YELLOW}Skipped,已跳过，按回车键返回。${RESET} " ;;
-	*) printf "%s\n" "${YELLOW}Invalid choice，skipped.已跳过，按回车键返回。${RESET} " ;;
-	esac
-	#tmoe_manager_main_menu
+    cd ${HOME}
+    for i in dev/shm dev/pts proc sys storage/emulated/0/* media/sd media/tf; do
+        if [ -e "${DEBIAN_CHROOT}/${i}" ]; then
+            ls -lAh "${DEBIAN_CHROOT}/${i}" 2>/dev/null
+        fi
+    done
+    unset i
+    check_rootfs_dir
+    grep ${DEBIAN_CHROOT} /proc/mounts
+    pkill -9 proot 2>/dev/null
+    pkill -9 chroot 2>/dev/null
+    ps -e | grep proot
+    ps -e | grep startvnc
+    printf "%s\n" "移除容器前，本工具将${RED}自动停止${RESET}${BLUE}${DEBIAN_FOLDER}${RESET}容器所运行的${GREEN}所有进程${RESET}。"
+    printf "%s\n" "Tmoe-linux manager will ${RED}automatically stop${RESET} ${GREEN}all processes${RESET} running in the ${BLUE}${DEBIAN_FOLDER}${RESET} container, and unmount the container directory."
+    pgrep proot &>/dev/null
+    if [ "$?" = "0" ]; then
+        printf '%s\n' '检测到proot容器正在运行，请先输stopvnc或手动强制停止容器运行'
+        #printf "%s\n" "若${ROOTFS_NAME}容器未停止运行，则建议你先手动在容器中执行stopvnc，再进行移除操作。"
+    fi
+    ls -l ${DEBIAN_CHROOT}/media/termux/* 2>/dev/null
+    if [ "$?" = "0" ]; then
+        printf '%s\n' 'WARNING！检测到/media/termux无法强制卸载，您当前使用的可能是chroot容器'
+        printf "%s\n" "若为误报，则请先停止容器进程，再手动移除${DEBIAN_CHROOT}/media/sd"
+        printf '%s\n' '建议您在移除前进行备份，若因操作不当而导致数据丢失，开发者概不负责！！！'
+    fi
+    printf "%s\n" "Detecting container size... 正在检测${ROOTFS_NAME}容器占用空间大小"
+    ${TMOE_PREFIX} du -sh ${DEBIAN_CHROOT} --exclude=${DEBIAN_CHROOT}/media/tf --exclude=${DEBIAN_CHROOT}/media/sd --exclude=${DEBIAN_CHROOT}/media/termux 2>/dev/null
+    if [ ! -d ${DEBIAN_CHROOT} ]; then
+        printf "%s\n" "${YELLOW}It is detected that you do not currently have GNU/Linux container installed. 检测到您当前未安装容器${RESET}"
+    fi
+    printf "%s\n" "Press ${GREEN}enter${RESET} to ${RED}remove${RESET}."
+    printf "%s\n" "按${GREEN}回车键${RESET}确认${RED}移除${RESET}"
+    printf "%s\n" "Do you want to remove it?${PURPLE}[Y/n]${RESET}"
+    read -r opt
+    case $opt in
+    y* | Y* | "")
+        #non-rm "${CONFIG_FOLDER}/chroot_container"
+        case ${TMOE_CHROOT} in
+        true)
+            sudo rm -rfv ${PREFIX}/bin/debian-rm ${PREFIX}/bin/code ~/.config/tmoe-linux/across_architecture_container.txt "${DEBIAN_CHROOT}"
+            sudo chmod 777 -Rv ${DEBIAN_CHROOT}
+            ;;
+        *)
+            rm -rfv ${PREFIX}/bin/debian-rm ${PREFIX}/bin/code ~/.config/tmoe-linux/across_architecture_container.txt "${DEBIAN_CHROOT}"
+            for i in ${PREFIX}/bin/debian-rm ${PREFIX}/bin/code ~/.config/tmoe-linux/across_architecture_container.txt; do
+                [[ ! -e ${i} ]] || sudo rm -rfv ${i}
+            done
+            chmod 777 -Rv ${DEBIAN_CHROOT} || sudo chmod 777 -Rv ${DEBIAN_CHROOT}
+            ;;
+        esac
+        rm -rfv "${DEBIAN_CHROOT}" || sudo rm -rfv "${DEBIAN_CHROOT}"
+        printf "%s\n" "如需删除（通用的）启动脚本，则请手动输${RED}rm -fv ${BLUE}${PREFIX}/bin/debian ${PREFIX}/bin/novnc ${PREFIX}/bin/debian-i ${PREFIX}/bin/tmoe ${PREFIX}/bin/startvnc ${PREFIX}/bin/startx11vnc ${PREFIX}/bin/stopvnc ${PREFIX}/bin/startxsdl${RESET}"
+        sed -i '/alias debian=/d ; /alias debian-rm=/d' ${PREFIX}/etc/profile 2>/dev/null
+        source profile >/dev/null 2>&1
+        #printf '%s\n' 'The container has been removed. If you want to uninstall aria2, enter "apt remove aria2" or "apt purge aria2"'
+        #printf '%s\n' '移除完成，如需卸载aria2,请手动输apt remove aria2'
+        printf "%s\n" "Deleted已删除"
+        ;;
+    n* | N*) printf "%s\n" "skipped." ;;
+    *) printf "%s\n" "Invalid choice. skipped." ;;
+    esac
+    #printf "%s\n" "若需删除tmoe-linux管理器，则请输rm -f ${PREFIX}/bin/debian-i"
+    printf '%s\n' 'If you want to reinstall, it is not recommended to remove the image file.'
+    printf "%s\n" "${YELLOW}若您需要重装容器，则不建议删除镜像文件。${RESET} "
+    cd ${ROOTFS_DIR}
+    DISTRO_ROOTFS_NAME=$(printf "%s\n" "${ROOTFS_NAME}" | cut -d '-' -f 1)
+    #${ROOTFS_NAME}*-rootfs.tar.*
+    ls -lh ${DISTRO_ROOTFS_NAME}*${ARCH_TYPE}*-rootfs.tar.* 2>/dev/null
+    printf "%s\n" "${YELLOW}请问您是否需要删除${BLUE}容器镜像文件？${PURPLE}[Y/n]${RESET} "
+    printf "%s\n" "${RED}rm -fv ${BLUE}${DISTRO_ROOTFS_NAME}*${ARCH_TYPE}*-rootfs.tar.*${RESET}"
+    printf "%s\n" "Do you need to delete the image file (${BLUE}${DISTRO_ROOTFS_NAME}*${ARCH_TYPE}*-rootfs.tar.*${RESET})?${PURPLE}[Y/n]${RESET}"
+    read -r opt
+    case $opt in
+    y* | Y* | "")
+        #rm -fv ${DEBIAN_CHROOT}*-rootfs.tar.*
+        #此处应删除ROOTFS_NAME而非DEBIAN_FOLDER开头的rootfs文件
+        rm -fv ${ROOTFS_DIR}/${DISTRO_ROOTFS_NAME}*${ARCH_TYPE}*-rootfs.tar.*
+        printf "%s\n" "Deleted已删除"
+        ;;
+    n* | N*) printf "%s\n" "${YELLOW}Skipped,已跳过，按回车键返回。${RESET} " ;;
+    *) printf "%s\n" "${YELLOW}Invalid choice，skipped.已跳过，按回车键返回。${RESET} " ;;
+    esac
+    #tmoe_manager_main_menu
 }
 ###################
 remove_gnu_linux_container
diff --git a/share/old-version/share/termux/termux b/share/old-version/share/termux/termux
--- a/share/old-version/share/termux/termux
+++ b/share/old-version/share/termux/termux
@@ -1,159 +1,159 @@
 #!/usr/bin/env bash
 ###########
 termux_tuna_sources_list() {
-	if ! grep -q '^deb.*bfsu.*' '/data/data/com.termux/files/usr/etc/apt/sources.list'; then
-		sed -i 's@^\(deb.*stable main\)$@#\1\ndeb https://mirrors.bfsu.edu.cn/termux/apt/termux-main stable main@' /data/data/com.termux/files/usr/etc/apt/sources.list
-		if ! grep -q '^deb' '/data/data/com.termux/files/usr/etc/apt/sources.list'; then
-			printf "%s\n" 'deb https://mirrors.bfsu.edu.cn/termux/apt/termux-main stable main' >>/data/data/com.termux/files/usr/etc/apt/sources.list
-		fi
-		[[ ${TUNA_MIRROR} != true ]] || sed -i -E 's@bfsu(.edu)@tuna.tsinghua\1@g' /data/data/com.termux/files/usr/etc/apt/sources.list
-	fi
+    if ! grep -q '^deb.*bfsu.*' '/data/data/com.termux/files/usr/etc/apt/sources.list'; then
+        sed -i 's@^\(deb.*stable main\)$@#\1\ndeb https://mirrors.bfsu.edu.cn/termux/apt/termux-main stable main@' /data/data/com.termux/files/usr/etc/apt/sources.list
+        if ! grep -q '^deb' '/data/data/com.termux/files/usr/etc/apt/sources.list'; then
+            printf "%s\n" 'deb https://mirrors.bfsu.edu.cn/termux/apt/termux-main stable main' >>/data/data/com.termux/files/usr/etc/apt/sources.list
+        fi
+        [[ ${TUNA_MIRROR} != true ]] || sed -i -E 's@bfsu(.edu)@tuna.tsinghua\1@g' /data/data/com.termux/files/usr/etc/apt/sources.list
+    fi
 
-	if [ -e "/data/data/com.termux/files/usr/etc/apt/sources.list.d/game.list" ]; then
-		if ! grep -q '^deb.*bfsu' '/data/data/com.termux/files/usr/etc/apt/sources.list.d/game.list'; then
-			sed -i 's@^\(deb.*games stable\)$@#\1\ndeb https://mirrors.bfsu.edu.cn/termux/apt/termux-games games stable@' /data/data/com.termux/files/usr/etc/apt/sources.list.d/game.list
-		fi
-		[[ ${TUNA_MIRROR} != true ]] || sed -i -E 's@bfsu(.edu)@tuna.tsinghua\1@g' /data/data/com.termux/files/usr/etc/apt/sources.list.d/game.list
-	fi
+    if [ -e "/data/data/com.termux/files/usr/etc/apt/sources.list.d/game.list" ]; then
+        if ! grep -q '^deb.*bfsu' '/data/data/com.termux/files/usr/etc/apt/sources.list.d/game.list'; then
+            sed -i 's@^\(deb.*games stable\)$@#\1\ndeb https://mirrors.bfsu.edu.cn/termux/apt/termux-games games stable@' /data/data/com.termux/files/usr/etc/apt/sources.list.d/game.list
+        fi
+        [[ ${TUNA_MIRROR} != true ]] || sed -i -E 's@bfsu(.edu)@tuna.tsinghua\1@g' /data/data/com.termux/files/usr/etc/apt/sources.list.d/game.list
+    fi
 
-	if [ -e "/data/data/com.termux/files/usr/etc/apt/sources.list.d/science.list" ]; then
-		if ! grep -q '^deb.*bfsu' '/data/data/com.termux/files/usr/etc/apt/sources.list.d/science.list'; then
-			sed -i 's@^\(deb.*science stable\)$@#\1\ndeb https://mirrors.bfsu.edu.cn/termux/apt/termux-science science stable@' /data/data/com.termux/files/usr/etc/apt/sources.list.d/science.list
-		fi
-		[[ ${TUNA_MIRROR} != true ]] || sed -i -E 's@bfsu(.edu)@tuna.tsinghua\1@g' /data/data/com.termux/files/usr/etc/apt/sources.list.d/science.list
-	fi
-	if [ -e "/data/data/com.termux/files/usr/etc/apt/sources.list.d/x11.list" ]; then
-		if ! grep -q '^deb.*bfsu' '/data/data/com.termux/files/usr/etc/apt/sources.list.d/x11.list'; then
-			sed -i 's@^\(deb.*x11 main\)$@#\1\ndeb https://mirrors.bfsu.edu.cn/termux/apt/termux-x11 x11 main@' /data/data/com.termux/files/usr/etc/apt/sources.list.d/x11.list
-		fi
-		[[ ${TUNA_MIRROR} != true ]] || sed -i -E 's@bfsu(.edu)@tuna.tsinghua\1@g' /data/data/com.termux/files/usr/etc/apt/sources.list.d/x11.list
-	fi
+    if [ -e "/data/data/com.termux/files/usr/etc/apt/sources.list.d/science.list" ]; then
+        if ! grep -q '^deb.*bfsu' '/data/data/com.termux/files/usr/etc/apt/sources.list.d/science.list'; then
+            sed -i 's@^\(deb.*science stable\)$@#\1\ndeb https://mirrors.bfsu.edu.cn/termux/apt/termux-science science stable@' /data/data/com.termux/files/usr/etc/apt/sources.list.d/science.list
+        fi
+        [[ ${TUNA_MIRROR} != true ]] || sed -i -E 's@bfsu(.edu)@tuna.tsinghua\1@g' /data/data/com.termux/files/usr/etc/apt/sources.list.d/science.list
+    fi
+    if [ -e "/data/data/com.termux/files/usr/etc/apt/sources.list.d/x11.list" ]; then
+        if ! grep -q '^deb.*bfsu' '/data/data/com.termux/files/usr/etc/apt/sources.list.d/x11.list'; then
+            sed -i 's@^\(deb.*x11 main\)$@#\1\ndeb https://mirrors.bfsu.edu.cn/termux/apt/termux-x11 x11 main@' /data/data/com.termux/files/usr/etc/apt/sources.list.d/x11.list
+        fi
+        [[ ${TUNA_MIRROR} != true ]] || sed -i -E 's@bfsu(.edu)@tuna.tsinghua\1@g' /data/data/com.termux/files/usr/etc/apt/sources.list.d/x11.list
+    fi
 
-	if [ -e "/data/data/com.termux/files/usr/etc/apt/sources.list.d/unstable.list" ]; then
-		if ! grep -q '^deb.*bfsu' '/data/data/com.termux/files/usr/etc/apt/sources.list.d/unstable.list'; then
-			sed -i 's@^\(deb.*unstable main\)$@#\1\ndeb https://mirrors.bfsu.edu.cn/termux/apt/termux-unstable unstable main@' /data/data/com.termux/files/usr/etc/apt/sources.list.d/unstable.list
-		fi
-		[[ ${TUNA_MIRROR} != true ]] || sed -i -E 's@bfsu(.edu)@tuna.tsinghua\1@g' /data/data/com.termux/files/usr/etc/apt/sources.list.d/unstable.list
-	fi
+    if [ -e "/data/data/com.termux/files/usr/etc/apt/sources.list.d/unstable.list" ]; then
+        if ! grep -q '^deb.*bfsu' '/data/data/com.termux/files/usr/etc/apt/sources.list.d/unstable.list'; then
+            sed -i 's@^\(deb.*unstable main\)$@#\1\ndeb https://mirrors.bfsu.edu.cn/termux/apt/termux-unstable unstable main@' /data/data/com.termux/files/usr/etc/apt/sources.list.d/unstable.list
+        fi
+        [[ ${TUNA_MIRROR} != true ]] || sed -i -E 's@bfsu(.edu)@tuna.tsinghua\1@g' /data/data/com.termux/files/usr/etc/apt/sources.list.d/unstable.list
+    fi
 
-	if [ -e "/data/data/com.termux/files/usr/etc/apt/sources.list.d/root.list" ]; then
-		if ! grep -q '^deb.*bfsu' '/data/data/com.termux/files/usr/etc/apt/sources.list.d/root.list'; then
-			sed -i 's@^\(deb.*root stable\)$@#\1\ndeb https://mirrors.bfsu.edu.cn/termux/apt/termux-root root stable@' /data/data/com.termux/files/usr/etc/apt/sources.list.d/root.list
-		fi
-		[[ ${TUNA_MIRROR} != true ]] || sed -i -E 's@bfsu(.edu)@tuna.tsinghua\1@g' /data/data/com.termux/files/usr/etc/apt/sources.list.d/root.list
-	fi
-	apt_dist_upgrade
-	press_enter_to_return
-	android_termux
-	#此处要返回依赖检测处！
+    if [ -e "/data/data/com.termux/files/usr/etc/apt/sources.list.d/root.list" ]; then
+        if ! grep -q '^deb.*bfsu' '/data/data/com.termux/files/usr/etc/apt/sources.list.d/root.list'; then
+            sed -i 's@^\(deb.*root stable\)$@#\1\ndeb https://mirrors.bfsu.edu.cn/termux/apt/termux-root root stable@' /data/data/com.termux/files/usr/etc/apt/sources.list.d/root.list
+        fi
+        [[ ${TUNA_MIRROR} != true ]] || sed -i -E 's@bfsu(.edu)@tuna.tsinghua\1@g' /data/data/com.termux/files/usr/etc/apt/sources.list.d/root.list
+    fi
+    apt_dist_upgrade
+    press_enter_to_return
+    android_termux
+    #此处要返回依赖检测处！
 }
 #############
 #此函数重复出现两次,另一次位于mirror
 apt_dist_upgrade() {
-	apt update
-	apt dist-upgrade -y
-	printf '%s\n' '修改完成，您当前的软件源列表如下所示。'
-	sed -n p /data/data/com.termux/files/usr/etc/apt/sources.list
-	sed -n p /data/data/com.termux/files/usr/etc/apt/sources.list.d/*
-	printf "%s\n" "您可以输${YELLOW}apt edit-sources${RESET}来手动编辑main源"
-	printf "%s\n" "您也可以输${YELLOW}cd ${PREFIX}/etc/apt/sources.list.d ; nano ./* ${RESET}来手动编辑其它源"
+    apt update
+    apt dist-upgrade -y
+    printf '%s\n' '修改完成，您当前的软件源列表如下所示。'
+    sed -n p /data/data/com.termux/files/usr/etc/apt/sources.list
+    sed -n p /data/data/com.termux/files/usr/etc/apt/sources.list.d/*
+    printf "%s\n" "您可以输${YELLOW}apt edit-sources${RESET}来手动编辑main源"
+    printf "%s\n" "您也可以输${YELLOW}cd ${PREFIX}/etc/apt/sources.list.d ; nano ./* ${RESET}来手动编辑其它源"
 }
 ######################
 switch_android_termux_mirror_to_bfsu() {
-	if ((ANDROID_VERSION >= 7)); then
-		unset TUNA_MIRROR
-		if ! grep -q '^deb.*edu.cn.*' '/data/data/com.termux/files/usr/etc/apt/sources.list'; then
-			printf "%s\n" "${YELLOW}检测到您当前使用的sources.list不是北外源,是否需要更换为北外源[Y/b/n]${RESET} "
-			printf "%s\n" "更换后可以加快中国境内的下载速度,${YELLOW}按回车键切换为bfsu北外源, 输t切换为tuna-tsinghua清华源，输n拒绝。${RESET}"
-			printf "%s\n" "If you are not living in the People's Republic of China, then please type ${YELLOW}n${RESET} .${PURPLE}[Y/n]${RESET}"
-			read -r opt
-			case $opt in
-			y* | Y* | "") termux_tuna_sources_list ;;
-			t* | T*)
-				TUNA_MIRROR=true
-				termux_tuna_sources_list
-				;;
-			n* | N*) printf "%s\n" "skipped." ;;
-			*) printf "%s\n" "Invalid choice. skipped." ;;
-			esac
-		fi
-	fi
+    if ((ANDROID_VERSION >= 7)); then
+        unset TUNA_MIRROR
+        if ! grep -q '^deb.*edu.cn.*' '/data/data/com.termux/files/usr/etc/apt/sources.list'; then
+            printf "%s\n" "${YELLOW}检测到您当前使用的sources.list不是北外源,是否需要更换为北外源[Y/b/n]${RESET} "
+            printf "%s\n" "更换后可以加快中国境内的下载速度,${YELLOW}按回车键切换为bfsu北外源, 输t切换为tuna-tsinghua清华源，输n拒绝。${RESET}"
+            printf "%s\n" "If you are not living in the People's Republic of China, then please type ${YELLOW}n${RESET} .${PURPLE}[Y/n]${RESET}"
+            read -r opt
+            case $opt in
+            y* | Y* | "") termux_tuna_sources_list ;;
+            t* | T*)
+                TUNA_MIRROR=true
+                termux_tuna_sources_list
+                ;;
+            n* | N*) printf "%s\n" "skipped." ;;
+            *) printf "%s\n" "Invalid choice. skipped." ;;
+            esac
+        fi
+    fi
 }
 ################
 android_termux() {
-	DEPENDENCIES=""
-	# busybox
-	for i in curl git pv grep pulseaudio proot tar zstd; do
-		#if [ ! -e "${PREFIX}/bin/${i}" ]; then
-		if [ ! "$(command -v ${i})" ]; then
-			DEPENDENCIES="${DEPENDENCIES} ${i}"
-		fi
-	done
-	if [[ ! $(command -v bat) && ! $(command -v batcat) ]]; then
-		DEPENDENCIES="${DEPENDENCIES} bat"
-	fi
-	if [ ! "$(command -v lsof)" ]; then
-		if ((ANDROID_VERSION < 7)); then
-			DEPENDENCIES="${DEPENDENCIES} busybox"
-		else
-			DEPENDENCIES="${DEPENDENCIES} lsof"
-		fi
-	fi
+    DEPENDENCIES=""
+    # busybox
+    for i in curl git pv grep pulseaudio proot tar zstd; do
+        #if [ ! -e "${PREFIX}/bin/${i}" ]; then
+        if [ ! "$(command -v ${i})" ]; then
+            DEPENDENCIES="${DEPENDENCIES} ${i}"
+        fi
+    done
+    if [[ ! $(command -v bat) && ! $(command -v batcat) ]]; then
+        DEPENDENCIES="${DEPENDENCIES} bat"
+    fi
+    if [ ! "$(command -v lsof)" ]; then
+        if ((ANDROID_VERSION < 7)); then
+            DEPENDENCIES="${DEPENDENCIES} busybox"
+        else
+            DEPENDENCIES="${DEPENDENCIES} lsof"
+        fi
+    fi
 
-	if ((ANDROID_VERSION >= 7)); then
-		i=micro
-		if [ ! "$(command -v ${i})" ]; then
-			DEPENDENCIES="${DEPENDENCIES} ${i}"
-		fi
-	fi
+    if ((ANDROID_VERSION >= 7)); then
+        i=micro
+        if [ ! "$(command -v ${i})" ]; then
+            DEPENDENCIES="${DEPENDENCIES} ${i}"
+        fi
+    fi
 
-	for i in termux-audio-info aria2c xz termux-setup-storage whiptail pkill which chroot unshare; do
-		if [ ! -e "${PREFIX}/bin/${i}" ]; then
-			case ${i} in
-			termux-audio-info) DEPENDENCIES="${DEPENDENCIES} termux-api" ;;
-			xz) DEPENDENCIES="${DEPENDENCIES} xz-utils" ;;
-			aria2c) DEPENDENCIES="${DEPENDENCIES} aria2" ;;
-			termux-setup-storage) DEPENDENCIES="${DEPENDENCIES} termux-tools" ;;
-			whiptail) DEPENDENCIES="${DEPENDENCIES} dialog" ;;
-			pkill) DEPENDENCIES="${DEPENDENCIES} procps" ;;
-			# which) DEPENDENCIES="${DEPENDENCIES} debianutils" ;;
-			chroot) DEPENDENCIES="${DEPENDENCIES} coreutils" ;;
-			unshare) DEPENDENCIES="${DEPENDENCIES} util-linux" ;;
-			esac
-		fi
-	done
+    for i in termux-audio-info aria2c xz termux-setup-storage whiptail pkill which chroot unshare; do
+        if [ ! -e "${PREFIX}/bin/${i}" ]; then
+            case ${i} in
+            termux-audio-info) DEPENDENCIES="${DEPENDENCIES} termux-api" ;;
+            xz) DEPENDENCIES="${DEPENDENCIES} xz-utils" ;;
+            aria2c) DEPENDENCIES="${DEPENDENCIES} aria2" ;;
+            termux-setup-storage) DEPENDENCIES="${DEPENDENCIES} termux-tools" ;;
+            whiptail) DEPENDENCIES="${DEPENDENCIES} dialog" ;;
+            pkill) DEPENDENCIES="${DEPENDENCIES} procps" ;;
+            # which) DEPENDENCIES="${DEPENDENCIES} debianutils" ;;
+            chroot) DEPENDENCIES="${DEPENDENCIES} coreutils" ;;
+            unshare) DEPENDENCIES="${DEPENDENCIES} util-linux" ;;
+            esac
+        fi
+    done
 
-	if [ ! -z "${DEPENDENCIES}" ]; then
-		[[ -s ${TMOE_LINUX_DIR}/TOOL_DEPENDENCIES.txt ]] || printf "%s\n" ${DEPENDENCIES} >${TMOE_LINUX_DIR}/TOOL_DEPENDENCIES.txt
-		[[ -s ${TMOE_LINUX_DIR}/MANAGER_DEPENDENCIES.txt ]] || printf "%s\n" ${DEPENDENCIES} >${TMOE_LINUX_DIR}/MANAGER_DEPENDENCIES.txt
-		case ${TMOE_LANG} in
-		zh_*UTF-8) switch_android_termux_mirror_to_bfsu ;;
-		*) ;;
-		esac
-		notes_of_tmoe_package_installation
-		apt update
-		apt install -y ${DEPENDENCIES}
-		case ${TERMUX_STORAGE} in
-		false) termux-setup-storage ;;
-		esac
-	fi
+    if [ ! -z "${DEPENDENCIES}" ]; then
+        [[ -s ${TMOE_LINUX_DIR}/TOOL_DEPENDENCIES.txt ]] || printf "%s\n" ${DEPENDENCIES} >${TMOE_LINUX_DIR}/TOOL_DEPENDENCIES.txt
+        [[ -s ${TMOE_LINUX_DIR}/MANAGER_DEPENDENCIES.txt ]] || printf "%s\n" ${DEPENDENCIES} >${TMOE_LINUX_DIR}/MANAGER_DEPENDENCIES.txt
+        case ${TMOE_LANG} in
+        zh_*UTF-8) switch_android_termux_mirror_to_bfsu ;;
+        *) ;;
+        esac
+        notes_of_tmoe_package_installation
+        apt update
+        apt install -y ${DEPENDENCIES}
+        case ${TERMUX_STORAGE} in
+        false) termux-setup-storage ;;
+        esac
+    fi
 
-	PULSE_AUDIO_PA="${PREFIX}/etc/pulse/default.pa"
-	PULSE_AUDIO_CONF="${PREFIX}/etc/pulse/daemon.conf"
+    PULSE_AUDIO_PA="${PREFIX}/etc/pulse/default.pa"
+    PULSE_AUDIO_CONF="${PREFIX}/etc/pulse/daemon.conf"
 
-	if ! grep -Eq '^[^#]*load-module module-native-protocol-tcp' ${PULSE_AUDIO_PA}; then
-		sed -i '/auth-ip-acl/d;/module-native-protocol-tcp/d' ${PULSE_AUDIO_PA}
-		sed -i '$a\load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1' ${PULSE_AUDIO_PA}
-		#sed -i '/module-native-protocol-tcp/d' ${PULSE_AUDIO_PA}
-		#grep -q "anonymous" ${PULSE_AUDIO_PA}
-		#printf "%s\n" "load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" >>${PULSE_AUDIO_PA}
-	fi
-	#auth-ip-acl=127.0.0.1;192.168.0.0/16时允许局域网内其它设备连接。
-	#auth-ip-acl不能是localhost，可以是127.0.0.1或0.0.0.0
-	if ! grep -Eq "^[^;]*exit-idle-time =" ${PULSE_AUDIO_CONF}; then
-		sed -i '/exit-idle/d;$ a\exit-idle-time = 3600' ${PULSE_AUDIO_CONF}
-	fi
-	# exit-idle-time 可设为-1
+    if ! grep -Eq '^[^#]*load-module module-native-protocol-tcp' ${PULSE_AUDIO_PA}; then
+        sed -i '/auth-ip-acl/d;/module-native-protocol-tcp/d' ${PULSE_AUDIO_PA}
+        sed -i '$a\load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1' ${PULSE_AUDIO_PA}
+        #sed -i '/module-native-protocol-tcp/d' ${PULSE_AUDIO_PA}
+        #grep -q "anonymous" ${PULSE_AUDIO_PA}
+        #printf "%s\n" "load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" >>${PULSE_AUDIO_PA}
+    fi
+    #auth-ip-acl=127.0.0.1;192.168.0.0/16时允许局域网内其它设备连接。
+    #auth-ip-acl不能是localhost，可以是127.0.0.1或0.0.0.0
+    if ! grep -Eq "^[^;]*exit-idle-time =" ${PULSE_AUDIO_CONF}; then
+        sed -i '/exit-idle/d;$ a\exit-idle-time = 3600' ${PULSE_AUDIO_CONF}
+    fi
+    # exit-idle-time 可设为-1
 }
 #############
 android_termux
diff --git a/share/old-version/tools/gui/configure_novnc b/share/old-version/tools/gui/configure_novnc
--- a/share/old-version/tools/gui/configure_novnc
+++ b/share/old-version/tools/gui/configure_novnc
@@ -1,67 +1,67 @@
 #######################
 configure_novnc() {
-	if [[ ! -s "${TMOE_LINUX_DIR}/achievement01" || ! -s /usr/local/bin/novnc ]]; then
-		printf "%s\n" "${PURPLE}尚未解锁${RESET}，您需要在获得成就“${BLUE}vnc大师${RESET}”后，才能对此选项进行配置。"
-		press_enter_to_return
-		modify_remote_desktop_config
-	fi
-	NOVNC_MAIN_DIR="${TMOE_LINUX_DIR}/novnc"
-	RETURN_TO_WHERE='configure_novnc'
-	TMOE_OPTION=$(
-		whiptail --title "CONFIGURE NOVNC" --menu "Type novnc to start novnc.输novnc启动novnc" 0 0 0 \
-			"1" "port端口" \
-			"2" "修改startnovnc启动脚本" \
-			"3" "remove 卸载/移除" \
-			"0" "🌚 Return to previous menu 返回上级菜单" \
-			3>&1 1>&2 2>&3
-	)
-	##############################
-	case "${TMOE_OPTION}" in
-	0 | "") modify_remote_desktop_config ;;
-	1) modify_novnc_port ;;
-	2)
-		check_editor
-		[[ -n ${EDITOR} ]] || EDITOR=nano
-		${EDITOR} /usr/local/bin/novnc
-		;;
-	3) remove_novnc ;;
-	esac
-	########################################
-	press_enter_to_return
-	configure_novnc
-	####################
+    if [[ ! -s "${TMOE_LINUX_DIR}/achievement01" || ! -s /usr/local/bin/novnc ]]; then
+        printf "%s\n" "${PURPLE}尚未解锁${RESET}，您需要在获得成就“${BLUE}vnc大师${RESET}”后，才能对此选项进行配置。"
+        press_enter_to_return
+        modify_remote_desktop_config
+    fi
+    NOVNC_MAIN_DIR="${TMOE_LINUX_DIR}/novnc"
+    RETURN_TO_WHERE='configure_novnc'
+    TMOE_OPTION=$(
+        whiptail --title "CONFIGURE NOVNC" --menu "Type novnc to start novnc.输novnc启动novnc" 0 0 0 \
+            "1" "port端口" \
+            "2" "修改startnovnc启动脚本" \
+            "3" "remove 卸载/移除" \
+            "0" "🌚 Return to previous menu 返回上级菜单" \
+            3>&1 1>&2 2>&3
+    )
+    ##############################
+    case "${TMOE_OPTION}" in
+    0 | "") modify_remote_desktop_config ;;
+    1) modify_novnc_port ;;
+    2)
+        check_editor
+        [[ -n ${EDITOR} ]] || EDITOR=nano
+        ${EDITOR} /usr/local/bin/novnc
+        ;;
+    3) remove_novnc ;;
+    esac
+    ########################################
+    press_enter_to_return
+    configure_novnc
+    ####################
 }
 ############
 remove_novnc() {
-	printf "%s\n" "${RED}pip3 uninstall ${BLUE}numpy websockify${RESET}"
-	printf "%s\n" "${RED}rm -rfv ${BLUE}${NOVNC_MAIN_DIR}${RESET}"
-	do_you_want_to_continue
-	pip3 uninstall numpy || sudo -H pip3 uninstall numpy
-	pip3 uninstall websockify || sudo -H pip3 uninstall websockify
-	rm -rfv ${NOVNC_MAIN_DIR} /usr/local/bin/novnc
+    printf "%s\n" "${RED}pip3 uninstall ${BLUE}numpy websockify${RESET}"
+    printf "%s\n" "${RED}rm -rfv ${BLUE}${NOVNC_MAIN_DIR}${RESET}"
+    do_you_want_to_continue
+    pip3 uninstall numpy || sudo -H pip3 uninstall numpy
+    pip3 uninstall websockify || sudo -H pip3 uninstall websockify
+    rm -rfv ${NOVNC_MAIN_DIR} /usr/local/bin/novnc
 }
 check_novnc_port() {
-	CURRENT_VALUE=$(grep '^NOVNC_PORT=' $(command -v novnc) | head -n 1 | awk -F '=' '{print $2}' | cut -d '"' -f 2)
+    CURRENT_VALUE=$(grep '^NOVNC_PORT=' $(command -v novnc) | head -n 1 | awk -F '=' '{print $2}' | cut -d '"' -f 2)
 }
 #############
 modify_novnc_port() {
-	check_novnc_port
-	TARGET=$(whiptail --inputbox "Please type the novnc port,the default is 36080,the current port is ${CURRENT_VALUE}" 10 50 --title "请输入端口" 3>&1 1>&2 2>&3)
-	if [ "$?" != "0" ]; then
-		configure_novnc
-	elif [ -z "${TARGET}" ]; then
-		printf "%s\n" "请输入有效的数值"
-		printf "%s\n" "Please enter a valid value"
-		check_novnc_port
-		printf "%s\n" "Current port is ${BLUE}${CURRENT_VALUE}${RESET}"
-	else
-		sed -i -E "s@^(NOVNC_PORT)=.*@\1=${TARGET}@" "$(command -v novnc)"
-		printf '%s\n' 'Your current port has been modified.'
-		#printf "%s\n" "您当前的分辨率已经修改为$(sed -n p $(command -v startnovnc) | grep 'TMOE_X11_RESOLUTION=' | head -n 1 | cut -d '=' -f 2)"
-		check_novnc_port
-		printf "%s\n" "The current port is ${BLUE}${CURRENT_VALUE}${RESET}"
-		printf "%s\n" "You can type ${GREEN}novnc${RESET} to restart it."
-	fi
+    check_novnc_port
+    TARGET=$(whiptail --inputbox "Please type the novnc port,the default is 36080,the current port is ${CURRENT_VALUE}" 10 50 --title "请输入端口" 3>&1 1>&2 2>&3)
+    if [ "$?" != "0" ]; then
+        configure_novnc
+    elif [ -z "${TARGET}" ]; then
+        printf "%s\n" "请输入有效的数值"
+        printf "%s\n" "Please enter a valid value"
+        check_novnc_port
+        printf "%s\n" "Current port is ${BLUE}${CURRENT_VALUE}${RESET}"
+    else
+        sed -i -E "s@^(NOVNC_PORT)=.*@\1=${TARGET}@" "$(command -v novnc)"
+        printf '%s\n' 'Your current port has been modified.'
+        #printf "%s\n" "您当前的分辨率已经修改为$(sed -n p $(command -v startnovnc) | grep 'TMOE_X11_RESOLUTION=' | head -n 1 | cut -d '=' -f 2)"
+        check_novnc_port
+        printf "%s\n" "The current port is ${BLUE}${CURRENT_VALUE}${RESET}"
+        printf "%s\n" "You can type ${GREEN}novnc${RESET} to restart it."
+    fi
 }
 #################
 configure_novnc $@
