feat(dotNET): add .NET6 compatible mode & .net container

diff --git a/share/old-version/share/container/proot/management b/share/old-version/share/container/proot/management
--- a/share/old-version/share/container/proot/management
+++ b/share/old-version/share/container/proot/management
@@ -153,6 +153,7 @@ environment_variables_and_automatic_startup_script_management() {
 			"13" "mount storage" \
 			"14" "mount tf" \
 			"15" "mount tmp(shared wayland socket)" \
+			"16" "dotNET6 compatible mode" \
 			"0" "🌚 Return to previous menu" \
 			3>&1 1>&2 2>&3)
 	}
@@ -174,6 +175,7 @@ environment_variables_and_automatic_startup_script_management() {
 				"13" "挂载storage" \
 				"14" "挂载tf" \
 				"15" "挂载tmp(共享wayland socket)" \
+				"16" "dotNET6 兼容模式" \
 				"0" "🌚 Return to previous menu" \
 				3>&1 1>&2 2>&3
 		)
@@ -238,10 +240,56 @@ environment_variables_and_automatic_startup_script_management() {
 		MOUNT_POINT_VAR="TMP_MOUNT_POINT"
 		mount_dir_to_container
 		;;
+	16) about_dot_net_6_compatible_mode ;;
 	esac
 	press_enter_to_return
 	environment_variables_and_automatic_startup_script_management
 }
+about_dot_net_6_compatible_mode() {
+	case ${TMOE_CHROOT} in
+	true)
+		printf "%s\n" \
+			"${RED}Sorry${RESET}, this feature only supports the rootless(proot) container." \
+			"Only rootless containers have this problem."
+		press_enter_to_return
+		environment_variables_and_automatic_startup_script_management
+		;;
+	*) ;;
+	esac
+	CURRENT_STATUS=$(grep -E "^[^#]*DOT_NET_6_COMPATIBLE_MODE=" ${TMOE_GNU_LINUX_CONTAINER_STARTUP_FILE} | awk -F '=' '{print $2}')
+
+	case ${CURRENT_STATUS} in
+	true) TMOE_TIPS_03="This mode is currently enabled" ;;
+	false) TMOE_TIPS_03="This mode is currently disabled" ;;
+	*) TMOE_TIPS_03="ERROR, unable to switch status.\nPlease reinstall the container." ;;
+	esac
+	case ${TMOE_MENU_LANG} in
+	zh*)
+		TMOE_TIPS_04="在某些环境中，您可能会遇到一些兼容问题。\n例如：在proot中(宿主:android, 容器:gnu/linux, 架构:arm64)，\n您在使用微软的 .NET6.0 时可能会遇到 \"csc.dll exited with code 139\"，\n没有找到 loader 等错误。注：.NET 7 没有此问题。\n在一般情况下，请不要开启此模式。"
+		YES_BUTTON="禁用"
+		NO_BUTTON="启用"
+		;;
+	*)
+		TMOE_TIPS_04="In some environments, you may encounter some strange compatibility issues.\nFor example: In proot(host: android, container: gnu/linux, arch: arm64), \nmicrosoft dotNET 6.0 may have \"csc.dll exited with code 139\" or \"loader not found\" when running a project.\nNote: dotNET 7 does not have this problem.\nIn general, you should not enable this mode."
+		YES_BUTTON="disable"
+		NO_BUTTON="enable"
+		;;
+	esac
+
+	if (whiptail --title "DOTNET6 COMP MODE" --yes-button "$YES_BUTTON" --no-button "$NO_BUTTON" --yesno "${TMOE_TIPS_03}" 0 50); then
+		${TMOE_PREFIX} sed -E -i "s@^(DOT_NET_6_COMPATIBLE_MODE=).*@\1false@" ${TMOE_GNU_LINUX_CONTAINER_STARTUP_FILE}
+	else
+		${TMOE_PREFIX} sed -E -i "s@^(DOT_NET_6_COMPATIBLE_MODE=).*@\1true@" ${TMOE_GNU_LINUX_CONTAINER_STARTUP_FILE}
+	fi
+	grep -E --color=auto "^[^#]*DOT_NET_6_COMPATIBLE_MODE=" ${TMOE_GNU_LINUX_CONTAINER_STARTUP_FILE}
+	printf "%s\n" \
+		"By the way, if it ${RED}cannot find${RESET} the dotnet bin. " \
+		"You should create a symlink ${PURPLE}in the container ${BLUE}manually${RESET}:" \
+		"${GREEN}mkdir ${YELLOW}-pv ${BLUE}\"${DEBIAN_CHROOT}\"/\${DOTNET_ROOT}" \
+		"${GREEN}rm ${YELLOW}-rv ${BLUE}\"${DEBIAN_CHROOT}\"/\${DOTNET_ROOT}" \
+		"${GREEN}ln ${YELLOW}-svf ${BLUE}\${DOTNET_ROOT} ${CYAN}\"${DEBIAN_CHROOT}\"/\${DOTNET_ROOT}${RESET}"
+}
+
 switch_to_chroot_or_unshare() {
 	case ${TMOE_CHROOT} in
 	true) ;;
@@ -341,7 +389,7 @@ change_the_mount_source_dir() {
 	do_you_want_to_continue
 }
 do_you_want_to_change_the_mount_source_dir() {
-	if (whiptail --title "SOURCE DIR" --yes-button "yes" --no-button "no" --yesno "Do you change the source dir?" 8 50); then
+	if (whiptail --title "SOURCE DIR" --yesno "Do you change the source dir?" 8 50); then
 		change_the_mount_source_dir
 	else
 		grep -E --color=auto "^[^#]*${MOUNT_SOURCE_VAR}=" ${TMOE_GNU_LINUX_CONTAINER_STARTUP_FILE}
@@ -363,7 +411,7 @@ mount_dir_to_container() {
 		case ${TMOE_CHROOT} in
 		true) ;;
 		*)
-			if (whiptail --title "MOUNT POINT" --yes-button "yes" --no-button "no" --yesno "Do you want to change the mount point?" 8 50); then
+			if (whiptail --title "MOUNT POINT" --yesno "Do you want to change the mount point?" 8 50); then
 				change_the_mount_point
 			else
 				grep -E --color=auto "^[^#]*${MOUNT_POINT_VAR}=" ${TMOE_GNU_LINUX_CONTAINER_STARTUP_FILE}
@@ -386,16 +434,20 @@ switch_login_shell() {
 	fi
 
 	CURRENT_SHELL=$(grep "^${LOGIN_SHELL_VAR}=" ${TMOE_GNU_LINUX_CONTAINER_STARTUP_FILE} | awk -F '=' '{print $2}')
+	local PWSH="/usr/share/powershell/pwsh"
+	local NUSH="/usr/local/cargo/bin/nu"
 	ENV_VAR_AND_SCRIPT=$(whiptail --title "You can switch the default login shell" --menu "The current login shell is ${CURRENT_SHELL}, default is zsh." 0 50 0 \
 		"1" "zsh" \
 		"2" "fish" \
-		"3" "bash" \
-		"4" "ash" \
-		"5" "sh" \
-		"6" "ksh" \
-		"7" "csh" \
-		"8" "pdksh" \
-		"9" "tcsh" \
+		"3" "pwsh:$PWSH" \
+		"4" "nu:$NUSH" \
+		"5" "bash" \
+		"6" "ash" \
+		"7" "sh" \
+		"8" "ksh" \
+		"9" "csh" \
+		"10" "pdksh" \
+		"11" "tcsh" \
 		"0" "🌚 Return to previous menu" \
 		3>&1 1>&2 2>&3)
 	##############################
@@ -403,13 +455,15 @@ switch_login_shell() {
 	0 | "") environment_variables_and_automatic_startup_script_management ;;
 	1) DEFAULT_SHELL=zsh ;;
 	2) DEFAULT_SHELL=fish ;;
-	3) DEFAULT_SHELL=bash ;;
-	4) DEFAULT_SHELL=ash ;;
-	5) DEFAULT_SHELL=sh ;;
-	6) DEFAULT_SHELL=ksh ;;
-	7) DEFAULT_SHELL=csh ;;
-	8) DEFAULT_SHELL=pdksh ;;
-	9) DEFAULT_SHELL=tcsh ;;
+	3) DEFAULT_SHELL=$PWSH ;;
+	4) DEFAULT_SHELL=$NUSH ;;
+	5) DEFAULT_SHELL=bash ;;
+	6) DEFAULT_SHELL=ash ;;
+	7) DEFAULT_SHELL="sh" ;;
+	8) DEFAULT_SHELL=ksh ;;
+	9) DEFAULT_SHELL=csh ;;
+	10) DEFAULT_SHELL=pdksh ;;
+	11) DEFAULT_SHELL=tcsh ;;
 	esac
 	${TMOE_PREFIX} sed -i -E "s@^(${LOGIN_SHELL_VAR}=).*@\1${DEFAULT_SHELL}@" ${TMOE_GNU_LINUX_CONTAINER_STARTUP_FILE}
 	grep -E --color=auto "^[^#]*${LOGIN_SHELL_VAR}=" ${TMOE_GNU_LINUX_CONTAINER_STARTUP_FILE}
@@ -502,12 +556,12 @@ switch_container_login_user() {
 	esac
 	case ${TMOE_MENU_LANG} in
 	zh_*UTF-8)
-		if (whiptail --title "DEFAULT USER" --yes-button "YES" --no-button "NO" --yesno "Do you want to set ${TMOE_USER_NAME} as the default user?\n请问您是否想要将${TMOE_USER_NAME}设置为默认用户?" 0 0); then
+		if (whiptail --title "DEFAULT USER" --yesno "Do you want to set ${TMOE_USER_NAME} as the default user?\n请问您是否想要将${TMOE_USER_NAME}设置为默认用户?" 0 0); then
 			set_tmoe_user_as_the_default_user
 		fi
 		;;
 	*)
-		if (whiptail --title "DEFAULT USER" --yes-button "YES" --no-button "NO" --yesno "Do you want to set ${TMOE_USER_NAME} as the default user?" 0 0); then
+		if (whiptail --title "DEFAULT USER" --yesno "Do you want to set ${TMOE_USER_NAME} as the default user?" 0 0); then
 			set_tmoe_user_as_the_default_user
 		fi
 		;;
@@ -1275,6 +1329,45 @@ network_node_menu_03() {
 # 		done
 # 	fi
 # }
+download_proot_arm64_deb() {
+	mkdir -pv "${TMOE_LINUX_DIR}/lib/"
+	cd "${TMOE_LINUX_DIR}/lib/"
+	# apt update
+	# apt-get download proot
+	apt-get download libtalloc
+	curl -Lo "proot-build-time.txt" l.tmoe.me/proot-aarch64-time
+	curl -Lo proot.deb l.tmoe.me/proot-aarch64 || echo "Sorry, unable to use compatible mode."
+
+	for i in ./libtalloc*.deb ./proot*.deb; do
+		dpkg-deb -X "${i}" ./
+		rm -fv "${i}"
+	done
+	cd -
+}
+get_android_proot_version() {
+	curl -Lo "${TMOE_LINUX_DIR}/lib/proot-build-time.txt" l.tmoe.me/proot-aarch64-time
+	local Local_build_time=$(head -n 1 "${TMOE_LINUX_DIR}"/lib/proot-build-time.txt)
+	lcoal Remote_build_time=$(curl -L --connect-timeout 3 --max-time 3 l.tmoe.me/proot-aarch64-time)
+	case "$Remote_build_time" in
+	"" | "${Local_build_time}") ;;
+	*) download_proot_arm64_deb ;;
+	esac
+}
+get_android_proot_arm64_deb() {
+	case ${LINUX_DISTRO} in
+	Android)
+		if [[ ${ARCH_TYPE} = arm64 ]]; then
+			PROOT_LOADER="${TMOE_LINUX_DIR}/lib/data/data/com.termux/files/usr/libexec/proot/loader"
+			if [[ ! -e ${PROOT_LOADER} ]]; then
+				echo "Your proot_loader is missing."
+				download_proot_arm64_deb
+			else
+				get_android_proot_version
+			fi
+		fi
+		;;
+	esac
+}
 install_weekly_build_container() {
 	case ${NODE01_ENABLED} in
 	true)
@@ -1319,6 +1412,10 @@ install_weekly_build_container() {
 	BUILD_TXT="${ARCH_TYPE}/${DISTRO_NAME_02}/${DESKTOP}/build.txt"
 	case ${TMOE_LANG} in
 	zh_*UTF-8) printf "%s\n" "正在获取版本信息..." ;;
+	esac
+
+	case ${DISTRO_NAME} in
+	dotnet*) get_android_proot_arm64_deb ;;
 	esac
 	printf "%s\n" "Getting ${DEBIAN_FOLDER} version info..."
 	ROOTFS_VERSION='latest02'
@@ -1397,6 +1494,7 @@ install_weekly_build_container() {
 			-e "1a\NODE02_PW=${NODE02_PW}" \
 			-e "1a\ROOTFS_VERSION=${ROOTFS_VERSION}" \
 			-e "1a\NODE_NAME=${NODE_NAME}" \
+			-e "1a\DISTRO_NAME=${DISTRO_NAME}" \
 			-e "s@TMOE_ROOTFS_TAR_XZ=.*debian-sid_.*@TMOE_ROOTFS_TAR_XZ=${ROOTFS_FILE}@" \
 			-e "s/debian container/${DISTRO_NAME} container/g" \
 			-e "s@BFSU Open Source Mirror Station@${NODE_NAME}@" \
diff --git a/share/old-version/share/container/proot/startup b/share/old-version/share/container/proot/startup
--- a/share/old-version/share/container/proot/startup
+++ b/share/old-version/share/container/proot/startup
@@ -16,16 +16,39 @@ cat >"${TMOE_STARTUP_SCRIPT}" <<-ENDOFPROOT
 	# 启动容器后进入的目录，默认为用户的主目录。请注意: 若您的默认 login shell 为 bash/zsh, 则请在“环境变量与登录项管理”处修改entrypoint。
 	WORK_DIR="default"
 	#------------------
-	# binary file
+	# binary file & compatibility
 
-	: <<-'EOF'
+	: <<-'EOF_compatibility_notes'
+	In some environments, you may encounter some strange compatibility issues.
+	For example: In proot(host: android, container: gnu/linux, arch: arm64), 
+	microsoft dotNET 6.0 may have "csc.dll exited with code 139" or "loader not found" when running a project.
+	Note: dotNET 7 does not have this problem.
+
+	In general, you should not enable this mode!!!
+
+	Enabling this mode forces the values of other variables to be overwritten.
+
+	if dot_net_6_compatible_mode = true {
+	    proot_bin = "compatibility",
+	    share_proot_loader = true,
+	};
+	By the way, if it cannot find the dotnet bin. You should create a symlink in the container manually:
+	mkdir -pv "${DEBIAN_CHROOT}"/\${DOTNET_ROOT} 
+	rm -rv "${DEBIAN_CHROOT}"/\${DOTNET_ROOT} 
+	ln -svf \${DOTNET_ROOT} "${DEBIAN_CHROOT}"/\${DOTNET_ROOT}
+	EOF_compatibility_notes
+	# true or false
+	DOT_NET_6_COMPATIBLE_MODE=false
+
+	: <<-'EOF_proot_bin_notes'
 	您可以自行编译proot, 并指定其二进制文件所在路径。当此变量值为"default"时，将使用系统默认proot二进制文件所在路径；当其为"termux"时，将使用 "\${PREFIX}/bin/proot"。
-	您也可以输入完整路径, 例如"/usr/local/bin/proot"
+	您也可以使用绝对路径, 例如"/usr/local/bin/proot"
 	You can specify the path where the binary file of proot is located. If the value is "default", it will use the default path of the system.
 	If the value is "32", it will use proot 32bit-version. If your host is arm64, and you want to run an i386/armhf container, then you can modify it to "32".
 
-	Note：若您使用了termux, 宿主机为64位(arm64)，容器(非虚拟机)为32位(i386/armhf)，则请使用32位版proot。如果arm64 termux使用了armhf版的proot，那么qemu-user-i386(arm64)也要切换为32位armhf版本。
-	若内核支持 binfmt_misc，且 host os 已经配置过 binfmt_misc 的 register，则您无需在此处进行额外的配置，且 container 没有那么多奇奇怪怪的问题。
+	Note：若内核支持 binfmt_misc，且 host os 已经配置过 binfmt_misc 的 register，则您无需在此处进行额外的配置，且 container 没有那么多奇奇怪怪的问题。
+
+	If your host os is already configured with binfmt_misc register, you don't have to worry about that much and the container doesn't have that many strange problems.
 
 	    // host_os == "android" && host_arch == "arm64":
 	    let (proot_bin_arch, qemu_bin_arch) = match (host_arch, host_os, container_arch) {
@@ -37,6 +60,7 @@ cat >"${TMOE_STARTUP_SCRIPT}" <<-ENDOFPROOT
 	        },
 	        ("arm64", "android", "armhf") => ("proot_armhf", "noqemu"),
 	        ("arm64", "android", "arm64") => ("proot_arm64", "noqemu"),
+	        ("arm64(without aarch32 support)", "android", "armhf") => ("proot_arm64", "qemu-user-arm-latest_arm64"),
 	    };
 
 	You can also enter an absolute path, for example, "\${PREFIX}/bin/proot"
@@ -44,20 +68,54 @@ cat >"${TMOE_STARTUP_SCRIPT}" <<-ENDOFPROOT
 	        "system" | "default" => "proot",
 	        "termux" => "${PREFIX}/bin/proot",
 	        "32" => PROOT_32_TERMUX_BIN, // "32" is &str, not i32/isize 
+	        "compatibility" => PROOT_COMPATIBLE_MODE_BIN,
 	        path @ _ => path,
 	    };
-	EOF
-	# Optional values: "default", "system", "termux", "32", or an absolute path.
+	EOF_proot_bin_notes
+	# Optional values: "default", "compatibility", "system", "termux", "32", or an absolute path.
 	PROOT_BIN="default"
 
+	# only for android (host_arch = arm64, container_arch = arm64)
+	# If you want to use COMPATIBLE_MODE on other platforms, compile proot manually and specify the path instead of using the default path.
+	# if proot_bin = "compatibility", proot_bin = "\$proot_compatible_mode_bin"
+	# value: an absolute path.
+	PROOT_COMPATIBLE_MODE_BIN="${TMOE_LINUX_DIR}/lib/data/data/com.termux/files/usr/bin/proot"
+
+	# if proot_bin = "32" && host_os = "android" {proot_bin = "\$proot_32_termux_bin"}
+	# value: an absolute path.
 	# PROOT_32_DEBIAN_BIN="${TMOE_LINUX_DIR}/lib32/usr/bin/proot"
 	PROOT_32_TERMUX_BIN="${TMOE_LINUX_DIR}/lib32/data/data/com.termux/files/usr/bin/proot"
 
+	# Some environments may have loader errors, for example: Microsoft dotNET 6.
+	# In this case, you need to share the proot loader.
+	# mount-src: proot_loader, mount-target: proot_loader
+	# true or false
+	SHARE_PROOT_LOADER=false
+
+	# proot loader
+	# if proot_bin = "default|system|path" {proot_loader = "\$proot_libexec_loader"}
+	# Optional values: "default", "system", or an absolute path.
 	PROOT_LIBEXEC_LOADER="default"
+
+	# only for android (host_arch = arm64, container_arch = "armhf|armel")
+	# if proot_bin = "32" {proot_loader = "\$proot_32_termux_loader"}
+	# value: an absolute path.
 	PROOT_32_TERMUX_LOADER="${TMOE_LINUX_DIR}/lib32/data/data/com.termux/files/usr/libexec/proot/loader"
 
+	# only for android (host_arch = arm64, container_arch = arm64)
+	# if proot_bin = "compatibility" {proot_loader = "\$compatible_mode_loader"}
+	# value: an absolute path.
+	COMPATIBLE_MODE_LOADER="${TMOE_LINUX_DIR}/lib/data/data/com.termux/files/usr/libexec/proot/loader"
+
+	# if proot_bin = "default|system|path" {ld_library_path = "\$ld_lib_path"}
 	LD_LIB_PATH="default"
+
+	# if proot_bin = "32" {ld_library_path = "\$proot_32_termux_ld_lib_path"}
+	# value: an absolute path.
 	PROOT_32_TERMUX_LD_LIB_PATH="${TMOE_LINUX_DIR}/lib32/data/data/com.termux/files/usr/lib"
+
+	# if proot_bin = "compatibility" {ld_library_path = "\$compatible_mode_ld_lib_path"}
+	COMPATIBLE_MODE_LD_LIB_PATH="${TMOE_LINUX_DIR}/lib/data/data/com.termux/files/usr/lib" 
 
 	ROOTFS_DIR="${DEBIAN_CHROOT}"
 	PROOT_PROC_DIR="\${ROOTFS_DIR}/usr/local/etc/tmoe-linux/proot_proc"
@@ -184,13 +242,18 @@ cat >"${TMOE_STARTUP_SCRIPT}" <<-ENDOFPROOT
 	# The default login shell is zsh.
 	# 默认登录shell是zsh
 	# Die Standard-Login-Shell ist zsh.
-	DEFAULT_LOGIN_SHELL_0="zsh"
+	DEFAULT_LOGIN_SHELL_0="/bin/zsh"
 
 	# The lower the number, the higher the priority.
-	DEFAULT_LOGIN_SHELL_1="fish"
-	DEFAULT_LOGIN_SHELL_2="bash"
-	DEFAULT_LOGIN_SHELL_3="ash"
-	DEFAULT_LOGIN_SHELL_4="su"
+	DEFAULT_LOGIN_SHELL_1="/bin/fish"
+	DEFAULT_LOGIN_SHELL_2="/bin/bash"
+	DEFAULT_LOGIN_SHELL_3="/bin/ash"
+	DEFAULT_LOGIN_SHELL_4="/bin/su"
+	# /usr/local/powershell/pwsh
+
+	# For zsh & bash, "-l" = "--login"
+	# For powershell & nushell, they do not have the "-l" arg.
+	LOGIN_SHELL_ARG="-l"
 	#------------------
 	# mounts
 
@@ -409,6 +472,25 @@ cat >"${TMOE_STARTUP_SCRIPT}" <<-ENDOFPROOT
 	        source \${STORAGE_CONF_FILE}
 		fi
 	}
+	get_proot_comp_mode_deb(){
+	    case \${HOST_DISTRO} in
+	    Android)
+	    if [[ \${HOST_ARCH} = arm64 && ! -e \${PROOT_LOADER} ]];then
+	        echo "ERROR, your proot_loader is missing."
+	        PROOT_LOADER="${TMOE_LINUX_DIR}/lib/data/data/com.termux/files/usr/libexec/proot/loader"
+	        mkdir -pv "${TMOE_LINUX_DIR}/lib/"
+	        cd "${TMOE_LINUX_DIR}/lib/"
+	        curl -Lo proot.deb l.tmoe.me/proot-aarch64 || echo "Sorry, unable to use compatible mode."
+	        apt-get download libtalloc
+	        for i in ./libtalloc*.deb ./proot*.deb; do
+	            dpkg-deb -X \${i} ./
+	            rm -fv \${i}
+	        done
+	        cd -
+	    fi
+	    ;;
+	    esac
+	} 
 	start_tmoe_gnu_linux_container() {
 	    load_global_conf
 	    unset LD_PRELOAD PROOT_UID PROOT_GID PROOT_HOME CONTAINER_BIN_PATH
@@ -488,6 +570,9 @@ cat >"${TMOE_STARTUP_SCRIPT}" <<-ENDOFPROOT
 	        if [[ \${OLD_ANDROID_VERSION_COMPATIBILITY_MODE} = true ]]; then
 	            PROOT_P=false && PROOT_L=false && PROOT_SYSVIPC=false && FAKE_KERNEL=true
 	        fi
+
+	        [[ \${SHARE_PROOT_LOADER} != true ]] || set -- "\${@}" "--mount=\${PROOT_LOADER}:\${EXA_PREFIX}\${PROOT_LOADER}"
+
 	        [[ \${PROOT_SYSVIPC} != true ]] || set -- "\${@}" "--sysvipc"
 	        [[ \${PROOT_L} != true ]] || set -- "\${@}" "-L"
 	        [[ \${PROOT_H} != true ]] || set -- "\${@}" "-H"
@@ -662,14 +747,24 @@ cat >"${TMOE_STARTUP_SCRIPT}" <<-ENDOFPROOT
 	    [[ \${EXA_ENABLED} != true ]] || set -- "\${@}" "LD_LIBRARY_PATH=/usr/local/lib:/usr/lib32:/usr/lib:/lib:/usr/lib/i386-linux-gnu:/var/lib:/var/lib/dpkg:/lib/i386-linux-gnu"
 	    #SHELL
 	    [[ ! -r \${DEFAULT_SHELL_CONF} ]] || source \${DEFAULT_SHELL_CONF}
-	    if [[ -z \${TMOE_SHELL} ]]; then
+
+	    case \${TMOE_SHELL} in
+	        "") 
 	        for i in \${DEFAULT_LOGIN_SHELL_0} \${DEFAULT_LOGIN_SHELL_1} \${DEFAULT_LOGIN_SHELL_2} \${DEFAULT_LOGIN_SHELL_3} \${DEFAULT_LOGIN_SHELL_4}; do
-	            if [[ -f \${ROOTFS_DIR}/bin/\${i} || -L \${ROOTFS_DIR}/bin/\${i} ]]; then
-	                TMOE_SHELL="/bin/\${i}"
+	            case "\$i" in
+	            */*) New_i="\$i";;
+	            *) New_i="/bin/\$i" ;;
+	            esac
+	            if [[ -f \${ROOTFS_DIR}\${New_i} || -L \${ROOTFS_DIR}\${New_i} ]]; then
+	                TMOE_SHELL="\${New_i}"
 	                break
 	            fi
-	        done
-	    fi
+	        done 
+			;;
+			*/*) ;;
+			*) TMOE_SHELL=/bin/\${TMOE_SHELL} ;;
+		esac
+
 	    set -- "\${@}" "SHELL=\${TMOE_SHELL}"
 	    #LOAD GLOBAL ENV FILE
 	    if [[ -s \${CONTAINER_ENV_FILE} && \${LOAD_ENV_FILE} = true ]]; then
@@ -690,13 +785,31 @@ cat >"${TMOE_STARTUP_SCRIPT}" <<-ENDOFPROOT
 	        set -- "\${@}" "PATH=\${CONTAINER_BIN_PATH}/usr/local/bin:/bin:/usr/bin:/usr/games:/usr/local/games"
 	    fi
 	    #LOGIN SHELL
-	    #It should be -l, not --login
-	    set -- "\${@}" "\${TMOE_SHELL}" "-l"
+	    case \${TMOE_SHELL} in
+	    */pwsh| */nushell| */nu) 
+	         case \${LOGIN_SHELL_ARG} in
+	         "-l") LOGIN_SHELL_ARG="" ;;
+	         esac
+	         ;;
+		esac
+
+		case "\${LOGIN_SHELL_ARG}" in
+		"") set -- "\${@}" "\${TMOE_SHELL}" ;;
+		*)  set -- "\${@}" "\${TMOE_SHELL}" "\${LOGIN_SHELL_ARG}" ;;
+		esac
 	    #------------------
 	    unset TMOE_LD_LIB_PATH
 	    case "\${PROOT_BIN}" in
 	    "" | system | default) PROOT_PROGRAM=proot ;;
 	    termux | prefix) PROOT_PROGRAM="\${PREFIX}/bin/proot" ;;
+	    compatibility)
+	        PROOT_PROGRAM="\${PROOT_COMPATIBLE_MODE_BIN}"
+	        SHARE_PROOT_LOADER=true
+	        PROOT_LOADER="\${COMPATIBLE_MODE_LOADER}"
+	        LD_LIB_PATH="\${COMPATIBLE_MODE_LD_LIB_PATH}"
+			# [[ -e \$COMPATIBLE_MODE_LD_LIB_PATH ]] || unset COMPATIBLE_MODE_LD_LIB_PATH
+	        get_proot_comp_mode_deb
+	        ;;
 	    32)
 	        case \${HOST_DISTRO} in
 	        Android)
